version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: sidezilla-filestorage
    command: minio server /data --address "0.0.0.0:12000" --console-address :9000
    ports:
      - 9000:9000
      - 12000:12000
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
      MINIO_REGION_NAME: us-east-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:12000/minio/health/live"]
      interval: 10s
      timeout: 7s
      retries: 5

  create_buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        /usr/bin/mc alias set --api "s3v2" sidezilla-storage http://minio:12000 root password;
        /usr/bin/mc mb sidezilla-storage/file-storage;
        /usr/bin/mc policy set public sidezilla-storage/file-storage;
        exit 0;
      "
